/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erp.view;

import com.erp.beans.Product;
import com.erp.beans.ProductQuantity;
import com.erp.dao.DAOException;
import com.erp.dao.DAOFactory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Jerome
 */
public class ProductPanel extends javax.swing.JPanel {

    private Product product;

    /**
     * Creates new form ProductPanel
     */
    public ProductPanel() {
        this.product = new Product();
        initComponents();

    }

    public ProductPanel(Product product, boolean editable) {
        initComponents();
        this.product = product;
        this.nameField.setText(product.getName());
        this.referenceField.setText(product.getReference());
        this.descriptionTextArea1.setText(product.getDescription());
        this.locationField.setText(product.getLocation());
        if (!editable) {
            JTable table = new JTable(new ProductQuantityTableModel(this.product.getProductQuantitys()));
            table.setFillsViewportHeight(true);
            this.JTablePanel.add(new JScrollPane(table));
            this.JTablePanel.repaint();
            this.JTablePanel.revalidate();
            this.nameField.setEditable(false);
            this.descriptionTextArea1.setEditable(false);
            this.locationField.setEditable(false);
            this.referenceField.setEditable(false);
            this.SaveButton.setEnabled(false);
        }
    }

    class ProductQuantityTableModel extends AbstractTableModel {

        private Object[][] data;
        private String[] columnNames = {"Id", "Batch number", "Serial number", "Quantity"};

        private ProductQuantityTableModel(ArrayList<ProductQuantity> productQuantitys) {
            data = new Object[productQuantitys.size()][4];
            for (int i = 0; i < productQuantitys.size(); i++) {
                data[i][0] = ""+productQuantitys.get(i).getId();
                data[i][1] = productQuantitys.get(i).getBatchNumber();
                data[i][2] = productQuantitys.get(i).getSerialNumber();
                data[i][3] = ""+productQuantitys.get(i).getQuantity();
            }
        }

        @Override
        public int getRowCount() {
            return this.data.length;
        }

        @Override
        public int getColumnCount() {
            return this.columnNames.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            return this.data[rowIndex][columnIndex];
        }

        public String getColumnName(int colIndex) {
            return this.columnNames[colIndex];
        }

        public Class getColumnClass(int c) {
            return getValueAt(0, c).getClass();
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PropertyPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        referenceLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        referenceField = new javax.swing.JTextField();
        descriptionScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea1 = new javax.swing.JTextArea();
        locationLabel = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        HeadPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        JTablePanel = new javax.swing.JPanel();

        nameLabel.setText("Name");

        referenceLabel.setText("Reference");

        descriptionLabel.setText("Description");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        descriptionTextArea1.setColumns(20);
        descriptionTextArea1.setRows(5);
        descriptionScrollPane1.setViewportView(descriptionTextArea1);

        locationLabel.setText("Location");

        javax.swing.GroupLayout PropertyPanelLayout = new javax.swing.GroupLayout(PropertyPanel);
        PropertyPanel.setLayout(PropertyPanelLayout);
        PropertyPanelLayout.setHorizontalGroup(
            PropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropertyPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(PropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addComponent(locationLabel)
                    .addComponent(referenceLabel)
                    .addComponent(nameLabel))
                .addGap(74, 74, 74)
                .addGroup(PropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        PropertyPanelLayout.setVerticalGroup(
            PropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropertyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(PropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referenceLabel))
                .addGap(18, 18, 18)
                .addGroup(PropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionLabel))
                .addGap(18, 18, 18)
                .addGroup(PropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(locationField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        HeadPanel1.setBackground(new java.awt.Color(204, 204, 204));

        TitleLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TitleLabel.setText("Product");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeadPanel1Layout = new javax.swing.GroupLayout(HeadPanel1);
        HeadPanel1.setLayout(HeadPanel1Layout);
        HeadPanel1Layout.setHorizontalGroup(
            HeadPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveButton)
                .addGap(117, 117, 117))
        );
        HeadPanel1Layout.setVerticalGroup(
            HeadPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeadPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JTablePanel.setLayout(new javax.swing.BoxLayout(JTablePanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PropertyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HeadPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeadPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PropertyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        this.product.setDescription(this.descriptionTextArea1.getText());
        this.product.setLocation(this.locationField.getText());
        this.product.setName(this.nameField.getText());
        this.product.setReference(this.referenceField.getText());

        String error = "";
        if (this.product.getName().isEmpty()) {
            error += "Name is required \n";
        }
        if (this.product.getLocation().isEmpty()) {
            error += "Location is required \n";
        }

        if (error.isEmpty()) {
            try {
                if (product.getId() != null) {
                    DAOFactory.getInstance().getProductDAO().update(product);
                } else {
                    DAOFactory.getInstance().getProductDAO().create(product);
                }
                this.removeAll();
                ProductsPanel panel = new ProductsPanel();
                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                this.repaint();
            } catch (DAOException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, error);
        }
//        this.removeAll();
//        ProductPanel panel = new ProductPanel();
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        this.setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        this.repaint();
    }//GEN-LAST:event_SaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeadPanel1;
    private javax.swing.JPanel JTablePanel;
    private javax.swing.JPanel PropertyPanel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollPane1;
    private javax.swing.JTextArea descriptionTextArea1;
    private javax.swing.JTextField locationField;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField referenceField;
    private javax.swing.JLabel referenceLabel;
    // End of variables declaration//GEN-END:variables
}
